"""
Sort a turtle file generated by rdflib.
"""

import os
import subprocess
import sys

directory = "ttl"


def sort_turtle_file(ttl_file):
    with open(ttl_file) as file:
        lines = file.readlines()

    # read in the file
    # lines = sys.stdin.readlines()
    if not lines:
        sys.exit(1)

    new_lines = ""
    chunks = []
    while lines:
        blank_line_index = 0
        try:
            blank_line_index = lines.index("\n")
        except ValueError:
            pass  # sort already done
        chunks.append(lines[0 : blank_line_index + 1])
        lines = lines[blank_line_index + 1 :]

    # print out the "# baseURI:" and "# imports:"
    new_lines += "".join(chunks[0][:-1])
    del chunks[0]

    # sort
    chunks.sort()

    # extract @prefix lines
    prefix_chunks = []
    prefix_indx = []
    for i, chunk in enumerate(chunks):
        if chunk[0].startswith("@prefix"):
            prefix_chunks.extend(chunk)
            prefix_indx.append(i)

    # remove the lines we found
    for i in reversed(prefix_indx):
        del chunks[i]

    # remove the blank lines
    prefix_chunks = [chunk for chunk in prefix_chunks if chunk != "\n"]

    # sort them and remove the duplicates
    prefix_chunks.sort()
    prefix_chunks = list(dict.fromkeys(prefix_chunks))
    new_lines += "".join(prefix_chunks)

    # print the rest
    for chunk in chunks:
        new_lines += "".join(chunk[:-1])

    with open(ttl_file, "w") as new_file:
        new_file.write(new_lines)


if __name__ == "__main__":
    # iterate over files in
    # that directory
    for filename in os.scandir(os.getcwd()):
        if filename.name.startswith("test_"):
            print("Making TTL")
            print(filename.path)
            subprocess.call(["python", filename.path])

    for filename in os.scandir(directory):
        if filename.is_file():
            print("Sorting TTL")
            print(filename.path)
            if filename.path.endswith(".ttl"):
                sort_turtle_file(filename.path)
