"""
Generate doc/glossary.md from ASHRAE 223P RDF (core.ttl, equipment.ttl).

Usage (from repo root):
  python tools/gen_glossary_from_rdf.py --models-dir "d:/0Programmes/Ashrae/223standard/models"

If --models-dir is omitted, it tries ../../223standard/models relative to this repo.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable

from rdflib import RDFS, Graph, Namespace, URIRef

S223 = Namespace("http://data.ashrae.org/standard223#")

# Core classes and relations referenced throughout the docs
CLASSES = [
    "Equipment",
    "System",
    "PhysicalSpace",
    "DomainSpace",
    "Zone",
    "Connectable",
    "Connection",
    "Junction",
    "ConnectionPoint",
    "InletConnectionPoint",
    "OutletConnectionPoint",
    "BidirectionalConnectionPoint",
    "Property",
    "ObservableProperty",
    "ActuatableProperty",
    "QuantifiableProperty",
    "QuantifiableObservableProperty",
    "QuantifiableActuatableProperty",
    "EnumerableProperty",
    "ExternalReference",
    "BACnetExternalReference",
    "Function",
    "Sensor",
]
RELATIONS = [
    "contains",
    "hasMember",
    "hasConnectionPoint",
    "isConnectionPointOf",
    "connected",
    "connectedTo",
    "connectedFrom",
    "connectsAt",
    "connectsThrough",
    "connectsTo",
    "connectsFrom",
    "cnx",
    "hasBoundaryConnectionPoint",
    "hasOptionalConnectionPoint",
    "mapsTo",
    "hasMedium",
    "hasRole",
    "hasObservationLocation",
    "hasReferenceLocation",
    "hasInternalReference",
    "hasExternalReference",
    "observes",
    "hasProperty",
    "hasInput",
    "hasOutput",
]


def load_graph(models_dir: Path) -> Graph:
    g = Graph()
    for fname in ("core.ttl", "equipment.ttl"):
        p = models_dir / fname
        if not p.is_file():
            raise FileNotFoundError(f"Missing {p}")
        g.parse(p.as_posix(), format="turtle")
    return g


def get_label(g: Graph, term: URIRef) -> str:
    for _, _, lbl in g.triples((term, RDFS.label, None)):
        return str(lbl)
    # fallback to localname
    return (
        term.split("#")[-1] if isinstance(term, str) else term.toPython().split("#")[-1]
    )


def get_comment(g: Graph, term: URIRef) -> str:
    for _, _, cmt in g.triples((term, RDFS.comment, None)):
        return str(cmt).strip()
    return ""


def md_anchor(name: str) -> str:
    return name.lower().replace(" ", "-")


def write_glossary(g: Graph, out_path: Path) -> None:
    lines = []
    lines.append("<!-- Do not edit: generated by tools/gen_glossary_from_rdf.py -->")
    lines.append("# Glossary (ASHRAE 223P terms)")
    lines.append("")
    lines.append(
        "This glossary is generated from the ASHRAE 223P RDF (core.ttl, equipment.ttl)."
    )
    lines.append("Links point to explore.open223.info for the canonical term page.")
    lines.append("")

    def emit_terms(header: str, names: Iterable[str], kind: str):
        lines.append(f"## {header}")
        lines.append("")
        for n in names:
            term = S223[n]
            label = get_label(g, term)
            comment = get_comment(g, term)
            url = f"https://explore.open223.info/s223/{n}"
            lines.append(f"### {label} (s223:{n})")
            lines.append(f"[Open223 term]({url})")
            lines.append("")
            if comment:
                lines.append(comment)
            else:
                lines.append(f"No description found in 223 RDF for s223:{n}.")
            lines.append("")
        lines.append("")

    emit_terms("Classes", CLASSES, "Class")
    emit_terms("Relations", RELATIONS, "Relation")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--models-dir",
        type=Path,
        default=None,
        help="Path to 223standard/models containing core.ttl and equipment.ttl",
    )
    args = ap.parse_args()

    # Default to ../../223standard/models relative to repo
    repo_root = Path(__file__).resolve().parents[1]
    models_dir = args.models_dir or (repo_root.parent / "223standard" / "models")
    g = load_graph(models_dir)

    out = repo_root / "doc" / "glossary.md"
    write_glossary(g, out)


if __name__ == "__main__":
    main()
