"""
Generate doc/equipment.md listing all concrete Equipment classes.

Usage:
  python tools/gen_equipment_docs.py

Options:
  --module-filter Fan,Coil   (substring filters)

Exclusions:
  - Package __init__.py modules are skipped (avoid pulling classes defined only to set namespace)
  - Classes whose names start with '_' or are dunder (e.g. __Something__) are skipped
  - Class names containing 'base', 'abstract', 'generic' (case-insensitive) are skipped
"""

from __future__ import annotations

import argparse
import importlib
import inspect
import pkgutil
from pathlib import Path
from typing import Iterable, Optional


def iter_equipment_modules() -> Iterable[str]:
    import bob.equipment  # noqa

    pkg = bob.equipment
    for m in pkgutil.walk_packages(pkg.__path__, pkg.__name__ + "."):
        yield m.name


def is_equipment_class(cls, equipment_base) -> bool:
    if not inspect.isclass(cls):
        return False
    name = cls.__name__
    if name.startswith("_") or (name.startswith("__") and name.endswith("__")):
        return False
    if equipment_base not in inspect.getmro(cls)[1:]:
        return False
    if getattr(cls, "__module__", "") != cls.__module__:
        return False
    lname = name.lower()
    if any(tok in lname for tok in ("base", "abstract", "generic")):
        return False
    return True


def extract_s223_term(cls) -> Optional[str]:
    """
    Attempt to extract the local s223 term name from a _class_iri / class_iri attribute.
    Accepts rdflib URIRef or NamespaceTerm; falls back to string parsing.
    """
    for attr in ("_class_iri", "class_iri", "CLASS_IRI"):
        iri = getattr(cls, attr, None)
        if iri is None:
            continue
        try:
            iri_str = str(iri)
        except Exception:
            continue
        if "#" in iri_str:
            local = iri_str.rsplit("#", 1)[-1]
        else:
            local = iri_str.rstrip("/").rsplit("/", 1)[-1]
        if local:
            return local
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--module-filter", help="Comma separated substrings to include modules"
    )
    args = ap.parse_args()
    module_filters = []
    if args.module_filter:
        module_filters = [
            s.strip().lower() for s in args.module_filter.split(",") if s.strip()
        ]

    from bob.core import Equipment as EquipmentBase  # type: ignore

    records = []
    # records entries: (status, module, class_name, signature, docline, s223_local_term)

    visited = set()
    for modname in sorted(set(iter_equipment_modules())):
        if module_filters and not any(f in modname.lower() for f in module_filters):
            continue
        if modname in visited:
            continue
        visited.add(modname)
        try:
            mod = importlib.import_module(modname)
        except Exception as e:
            records.append(("WARN", modname, f"import failed: {e}", "", "", None))
            continue

        mod_file = getattr(mod, "__file__", "") or ""
        if mod_file.endswith("__init__.py") or mod_file.endswith("__init__.pyc"):
            continue

        for cname, cls in inspect.getmembers(mod, inspect.isclass):
            if not is_equipment_class(cls, EquipmentBase):
                continue
            try:
                sig = str(inspect.signature(cls.__init__)).replace("(self, ", "(")
            except Exception:
                sig = "(...)"
            doc = (inspect.getdoc(cls) or "").splitlines()
            docline = doc[0] if doc else ""
            s223_term = extract_s223_term(cls)
            records.append(("OK", modname, cname, sig, docline, s223_term))

    repo_root = Path(__file__).resolve().parents[1]
    out = repo_root / "doc" / "equipment.md"
    lines = []
    lines.append("<!-- Do not edit: generated by tools/gen_equipment_docs.py -->")
    lines.append("# Built-in Equipment Classes")
    lines.append("")
    lines.append(
        "Auto-generated list of concrete s223:Equipment subclasses (excluding package __init__ and private/abstract classes)."
    )
    lines.append(
        "Each entry links to its ASHRAE 223P term on explore.open223.info when a _class_iri was found."
    )
    lines.append("")
    current_mod = None
    for status, mod, cname, sig, docline, s223_term in records:
        if status != "OK":
            lines.append(f"- [WARN] {mod}: {cname}")
            continue
        if mod != current_mod:
            lines.append(f"## {mod}")
            current_mod = mod
        lines.append(f"### {cname}")
        lines.append(f"- Signature: `{cname}{sig}`")
        if docline:
            lines.append(f"- Summary: {docline}")
        if s223_term:
            lines.append(
                f"- s223 term: `{s223_term}`  (<https://explore.open223.info/s223/{s223_term}>)"
            )
        else:
            lines.append("- s223 term: (not declared via _class_iri)")
        lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
